services:
  zipcodes:
    image: zipcodes:latest
    container_name: zipcodes
    restart: unless-stopped
    environment:
      - PORT=8080
    volumes:
      - ./data:/data
      - ./config:/config
      - ./logs:/logs
    ports:
      - "8080:8080"
    healthcheck:
      test: ["zipcodes", "--status"]
      interval: 30s
      timeout: 3s
      retries: 3
