site_name: Zipcodes Documentation
site_description: ZIP/postal codes database API with GeoIP integration and geographic search
site_author: apimgr
site_url: https://zipcodes.readthedocs.io

repo_name: apimgr/zipcodes
repo_url: https://github.com/apimgr/zipcodes
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 apimgr

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: dracula
    primary: deep purple
    accent: pink
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - API Reference: API.md
  - Server Guide: SERVER.md
  - GitHub: https://github.com/apimgr/zipcodes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - toc:
      permalink: true
  - tables
  - attr_list

plugins:
  - search
  - minify:
      minify_html: true

extra_css:
  - stylesheets/dracula.css

extra_javascript:
  - javascripts/extra.js
